### ISSUE TITLE
How to encode back?

### ISSUE THREAD

**Issue by Chweyaa** [raleighlittles/AAMVA_Drivers_License_Decoder#1]
Is there a way to encode it back to the PDF417 format?

**Comment by raleighlittles** [comment]
Using this repository? No, there isn't a way to do that using the code here. The easiest way would just be to copy the text into one of the many free online PDF 417 barcode generators: https://barcode.tec-it.com/en/PDF417

Or try to search for a Python library that could do this, I'm sure there's probably a few out there that can. @Chweyaa
